POST http://localhost:8080/api/shorten/batch
Content-Type: application/json

[
  {
    "correlation_id": "123",
    "original_url": "http://am123.com"
  },
  {
    "correlation_id": "123",
    "original_url": "http://am125.com"
  },
  {
    "correlation_id": "123",
    "original_url": "http://am124.com"
  }
]

###
