# curl -X POST -H "Content-Type: text/plain" -d "http://google.com" http://localhost:8080
POST http://localhost:8080
Content-Type: text/plain

http://google.com

###

POST http://localhost:8080
Content-Type: text/plain

http://google1.com

###

POST http://localhost:8080
Content-Type: text/plain

http://google2.com

###

POST http://localhost:8080
Content-Type: text/plain

http://google3.com

###

